document.writeln('<div class="header">')
document.writeln('<a class="logo" href="index.html" target="_self"></a>')
document.writeln('<ul id="nav">')
document.writeln('<li><a href="#">品牌故事</a>')
document.writeln('</li>')
document.writeln('<li><a href="#">关于明康</a>')
document.writeln('<ul class="children">')
document.writeln('<li><a href="#">集团简介</a>')
document.writeln('<ul class="children">')
document.writeln('<li><a href="#">明康汇</a></li>')
document.writeln('<li><a href="h#">农业集团</a></li>')
document.writeln('<li><a href="h#">海亮集团</a></li>')
document.writeln('</ul>')
document.writeln('</li>')
document.writeln('<li><a href="#">品牌诠释</a>')
document.writeln('</li>')
document.writeln('<li><a href="news.html">新闻公告</a>')
document.writeln('</li>')
document.writeln('</ul>')
document.writeln('</li>')
document.writeln('<li><a href="#">全产业链</a>')
document.writeln('<ul class="children">')
document.writeln('<li><a href="#">产业链概述</a></li>')
document.writeln('<li><a href="#">农业基地</a></li>')
document.writeln('<li><a href="#">食品加工</a></li>')
document.writeln('<li><a href="#">质量检测</a></li>')
document.writeln('<li><a href="#">物流配送</a></li>')
document.writeln('<li><a href="#">门店</a></li>')
document.writeln('</ul>')
document.writeln('</li>')
document.writeln('<li><a href="#">精彩活动</a></li>')
document.writeln('<li><a href="exposure.html">招贤纳士</a></li>')
document.writeln('<li><a href="exposure.html">诚信曝光</a></li>')
document.writeln('</ul>')
document.writeln('</div>')



