<?php return array (
  'name' => '默认模板',
  'author' => 'PHPCMS TEAM',
  'dirname' => 'default',
  'homepage' => 'http://www.phpcms.cn/',
  'version' => '1.0',
  'disable' => 0,
  'file_explan' => 
  array (
    'templates|default|content' => 
    array (
      'category.html' => '',
      'category_download.html' => '',
      'category_picture.html' => '',
      'category_video.html' => '',
      'category_xwgg.html' => '',
      'download.html' => '',
      'footer.html' => '',
      'header.html' => '',
      'header_min.html' => '',
      'header_page.html' => '',
      'index.html' => '',
      'list.html' => '',
      'list_download.html' => '',
      'list_picture.html' => '',
      'list_video.html' => '',
      'message.html' => '',
      'page.html' => '',
      'play_list.html' => '',
      'rss.html' => '',
      'search.html' => '',
      'show.html' => '',
      'show_cxbg_yjfk.html' => '诚信曝光-意见反馈',
      'show_download.html' => '',
      'show_mksjfs_app.html' => '明康汇社交方式-APP',
      'show_mksjfs_wx.html' => '明康汇社交方式-微信',
      'show_picture.html' => '',
      'show_video.html' => '',
      'show_videolist.html' => '',
      'tag.html' => '',
      'tag_list.html' => '',
      'video_album.html' => '',
      'video_for_ck.html' => '',
    ),
  ),
);?>